### ISSUE TITLE
Is it up to date?

### ISSUE THREAD

**Issue by jcesarmobile** [iSpeech/iSpeech-iOS-SDK#1]
Last version I saw on iSpeech website was dated 10/12/2016 (I think that's Oct 12 2016), but latest commit here is from "Jan 13 2016", so it looks quite older than the latest published version.

**Comment by mdifabio-ispeech** [comment]
Hey,  the version in the repository and the version on the site are the same.

**Comment by jcesarmobile** [comment]
The site now points to this github repo, but last time I checked, when you could download the SDK from the site, it said that the version was updated on 10/12/2016

**Comment by mdifabio-ispeech** [comment]
That is correct.  The commit date in January is because that is the date we moved the project to GitHub.

**Comment by jcesarmobile** [comment]
I've created a PR with latest libiSpeechSDK.a file I downloaded from the website on 10/12/2016 and it's smaller than the one you have on the repo. https://github.com/iSpeech/iSpeech-iOS-SDK/pull/2
So, can you make sure that you have the latest libiSpeechSDK.a here? 
Previous one I had, had the same size as the one on the repo, so I think it's not updated.

**Comment by jcesarmobile** [comment]
ping
